title = "Yazeed's Blog"
description = "Notes on systems and low-level software."
base_url = "https://yazeed1s.github.io"
compile_sass = false
build_search_index = false
default_language = "en"
taxonomies = [{ name = "tags", feed = true }]

[markdown]
[markdown.highlighting]
highlight_code_in_css = true
extra_themes = [
  "themes/gruvbox-custom-dark.json",
  "themes/gruvbox-custom-light.json",
]
light_theme = "Gruvbox Material Light"
dark_theme = "Gruvbox Material Dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
# SEO
keywords = "yazeed, blog, alharthi, yaz, yazeed1s"
# site_icon = "quill.svg"
# strapline = "#"
# footer_text = "austere - made for <a href='https://getzola.org'>Zola</a>"
favicon = "/favicon.ico"
# profile_picture = "/images/profile.svg"
recent_posts_count = 5

inline_icons = true
icon_path = "static/icons/"
icons = ["light", "asleep", "rss"]

image_format = "auto"
image_quality = 100
images_default_size = 1024
images_sizes = [512, 1024, 2048]

# menu.
menu_links = [
  { url = "$BASE_URL/", name = "Home" },
  { url = "$BASE_URL/posts/", name = "Posts" },
  # { url = "$BASE_URL/about/", name = "About" },
  { url = "$BASE_URL/projects/", name = "Projects" },
  { url = "$BASE_URL/tags/", name = "Tags" },
  # { url = "$BASE_URL/search/", name = "Search" },
]


[extra.colours.light]
background = "#eae6deff"
text = "#1a1410"
text_muted = "#1a1410"
accent = "#9E4440"
accent_hover = "#7A3533"
code_bg = "#e1ded6ff"
border = "#abaaaaff"

[extra.colours.dark]
background = "#303132"
text = "#bebbb9ff"
text_muted = "#d5d2cf"
accent = "#e57665"
accent_hover = "#888885"
code_bg = "#282829"
border = "#524f4c"
