title = "Yazeed's Blog"
description = "A minimal theme for Zola with a focus on writing."
base_url = "https://example.com"
compile_sass = false
build_search_index = false
default_language = "en"
taxonomies = [{ name = "tags", feed = true }]
[markdown]
[markdown.highlighting]
highlight_code_in_css = true
light_theme = "gruvbox-light-hard"
dark_theme = "kanagawa-dragon"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
# Keywords for SEO.
keywords = "yazeed, blog, alharthi, yaz, yazeed1s"
# Site icon in header (optional - comment out to hide).
# site_icon = "quill.svg"
# Header strapline (optional - comment out to hide).
strapline = "#"
# Footer text (optional - comment out to hide).
# footer_text = "austere - made for <a href='https://getzola.org'>Zola</a>"
# Favicon (optional - comment out to hide).
favicon = "/favicon.ico"
# Profile picture on home page (optional - comment out to hide).
profile_picture = "/images/profile.svg"

# Enable inline SVG icons (uses sprite sheet).
inline_icons = true
icon_path = "static/icons/"
icons = ["light", "asleep", "rss"]

# Responsive images
image_format = "auto"
image_quality = 80
images_default_size = 1024
images_sizes = [512, 1024, 2048]

# Navigation menu.
menu_links = [
  { url = "$BASE_URL/", name = "Home" },
  { url = "$BASE_URL/posts/", name = "Posts" },
  { url = "$BASE_URL/about/", name = "About" },
  { url = "$BASE_URL/projects/", name = "Projects" },
  { url = "$BASE_URL/tags/", name = "Tags" },
  # { url = "$BASE_URL/search/", name = "Search" },
]

# Custom colour themes. Adjust here to apply own colour.
# Light colours.
[extra.colours.light]
background = "#D4CEC0"
text = "#1a1410"
text_muted = "#1a1410"
accent = "#9E4440"
accent_hover = "#7A3533"
code_bg = "#cac4b8ff"
border = "#abaaaaff"
# Dark colours.
[extra.colours.dark]
background = "#303132"
text = "#d5d2cf"
text_muted = "#d5d2cf"
accent = "#e57665"
accent_hover = "#888885"
code_bg = "#282829"
border = "#524f4c"
